slack:
    webhookfile: webhook.secret

pressure_sensor:
    offset: 0.504140385
    min: 1.6
    max: 4.5

monitor:
    threshold: 2
    frequency: 10
    unit: ureg.second

debug:
    loglevel: DEBUG
