slack:
    webhookfile: webhook.secret

pressure_sensor:
    offset: 0.504140385
    min: 1.6
    max: 4.5

monitor:
    lo: 0.5
    hi: 2.0
    frequency: 0.25
    unit: minute
    window: 5

debug:
    loglevel: DEBUG
